// Date: 7/18/2015 6:19:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.nate.turrets.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class BasicTurretModel extends ModelBase
{
    //fields
    ModelRenderer stand;
    ModelRenderer base;
    ModelRenderer rotator;
    ModelRenderer nozzel;
    ModelRenderer nozzelPiece;
    ModelRenderer ammoBox;

    public BasicTurretModel()
    {
        textureWidth = 64;
        textureHeight = 32;

          stand = new ModelRenderer(this, 12, 18);
          stand.addBox(-1F, 0F, -1F, 2, 3, 2);
          stand.setRotationPoint(0F, 20F, 3F);
          stand.setTextureSize(64, 32);
          stand.mirror = true;
          setRotation(stand, 0.0174533F, 0F, 0F);
          base = new ModelRenderer(this, 0, 23);
          base.addBox(-4F, 0F, -4F, 8, 1, 8);
          base.setRotationPoint(0F, 23F, 3F);
          base.setTextureSize(64, 32);
          base.mirror = true;
          setRotation(base, 0F, 0F, 0F);
          rotator = new ModelRenderer(this, 8, 13);
          rotator.addBox(-2F, 2F, -2F, 4, 1, 4);
          rotator.setRotationPoint(0F, 17F, 3F);
          rotator.setTextureSize(64, 32);
          rotator.mirror = true;
          setRotation(rotator, 0F, -0.0174533F, 0F);
          nozzel = new ModelRenderer(this, 40, 2);
          nozzel.addBox(-1F, -1F, -11.5F, 2, 2, 7);
          nozzel.setRotationPoint(0F, 17F, 3.046667F);
          nozzel.setTextureSize(64, 32);
          nozzel.mirror = true;
          setRotation(nozzel, -0.0174533F, -0.0174533F, 0F);
          nozzelPiece = new ModelRenderer(this, 30, 4);
          nozzelPiece.addBox(-1.5F, -1.5F, -5F, 3, 3, 2);
          nozzelPiece.setRotationPoint(0F, 17F, 3F);
          nozzelPiece.setTextureSize(64, 32);
          nozzelPiece.mirror = true;
          setRotation(nozzelPiece, -0.0174533F, 0F, 0F);
          ammoBox = new ModelRenderer(this, 2, 1);
          ammoBox.addBox(-3F, -2F, -3.5F, 6, 4, 8);
          ammoBox.setRotationPoint(0F, 17F, 3F);
          ammoBox.setTextureSize(64, 32);
          ammoBox.mirror = true;
          setRotation(ammoBox, -0.0174533F, -0.0174533F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        stand.render(f5);
        base.render(f5);
        rotator.render(f5);
        nozzel.render(f5);
        nozzelPiece.render(f5);
        ammoBox.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

    public void rotateTop(float x, float y, float z){
        setRotation(rotator, x, y , z);
        setRotation(nozzel, x, y, z);
        setRotation(nozzelPiece, x, y, z);
        setRotation(ammoBox, x, y, z);
    }

}
